### ISSUE TITLE
麻烦作者帮我看看这个问题。谢谢！

### ISSUE THREAD

**Issue by wenwen19910224** [striderdu/SPA#1]
2023-12-11 14:20:24,003 - _8_22_all - [INFO] - Namespace(arch='', arch_learning_rate=0.01, arch_sample_num=1000, arch_weight_decay=0.001, base_num=0, baseline_sample_num=30, batch_size=8, comp_op='corr', dataset='icews14/', dataset_dir='datasets/', dropout=0.1, embed_size=128, encoder='', fixed_ops='', gnn_layer_num=3, grad_clip=1, head_num=4, hidden_size=128, index=1, inv_temperature=0.1, isolated_change=False, learning_rate=0.005, log_dir='logs/', max_epoch=200, min_arch_learning_rate=0.0005, min_learning_rate=0.001, momentum=0.9, negative_sampling_num=500, optimizer='adam', positive_fact_num=3000, random_seed=22, rec_only_last_layer=True, rnn_layer_num=1, sampled_dataset=False, save_model=False, saved_model_dir='saved_models/', score_function='complex', search_max_epoch=800, search_mode='', search_res_dir='searched_res/', search_res_file='', search_run_num=1, seq_head_num=4, stand_alone_path='', tensorboard_dir='tensorboard/', test_seq_len=8, time_log_dir='', train_mode='train', train_seq_len=8, tune_res_dir='tune_res/', tune_sample_num=20, unrolled=False, use_time_embedding=False, weight_decay=0.0005, weight_path='')
Traceback (most recent call last):
  File "C:/code/SPA-main/main.py", line 136, in <module>
    main()
  File "C:/code/SPA-main/main.py", line 92, in main
    trainer.train()
  File "C:\code\SPA-main\trainer.py", line 46, in train
    model = MODEL[self.args.encoder](self.args, self.dataset_info_dict, self.device)
KeyError: ''

**Comment by striderdu** [comment]
hi, @wenwen19910224,

Thanks for your interest in our work.

From the logs, it seems you didn't assign the encoder argument. You can follow instructions in README.md to run it.

If you have any questions, feel free to contact me.

Thanks!

**Comment by wenwen19910224** [comment]
Ok, I have solved this problem, thank you for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "striderdu/SPA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月13日(星期三) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [striderdu/SPA] 麻烦作者帮我看看这个问题。谢谢！ (Issue #1)





 
hi, @wenwen19910224,
 
Thanks for your interest in our work.
 
From the logs, it seems you didn't assign the encoder argument. You can follow instructions in README.md to run.
 
If you have any questions, feel free to contact me.
 
Thanks!
