### ISSUE TITLE
作者您好，我遇到了一个问题

### ISSUE THREAD

**Issue by y17733806775** [striderdu/SPA#2]
2024-01-14 01:17:16,174 - _search_22 - [INFO] - The search process costs 14.38h.
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    main()
  File "main.py", line 122, in main
    with open(args.search_res_dir + args.dataset + args.search_mode + f'/{start_running_time}.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'searched_res/icews14/spos_search/20240113_105435.json'

architecture search阶段进行完之后，程序没有保存相应的搜索结果，请问我要如何解决呢？感谢您的回复。

**Comment by y17733806775** [comment]
thank you
